version: '3.7'

services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - front-server
      - api-server
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf

  front-server:
    image: jusuk/simple-front-server:latest
    depends_on:
      - api-server

  api-server:
    image: nginx:latest
    depends_on:
      - auth-server
      - alarm-server
      - goods-server
    volumes:
      - ./api-server/default.conf:/etc/nginx/conf.d/default.conf

  auth-server:
    image: jusuk/auth-server:latest
    depends_on:
      - session-db-server
    
  session-db-server:
    image: jusuk/session-db-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: passwd
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -uadnin -ppasswd SESSION_DB
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  goods-server:
    image: jusuk/goods-server:latest
    depends_on:
      - "auth-server"

  alarm-server:
    image: jusuk/alarm-server:latest
    depends_on:
      - "auth-server"