version: '2'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - front-server
      - api-server
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf

  front-server:
    image: nginx:latest
    ports:
      - "20080:80"
    depends_on:
      - api-server

  api-server:
    image: nginx:latest
    ports:
      - "30080:80"
    depends_on:
      - auth-server
      - alarm-server
      - goods-server
    volumes:
      - ./api-server/default.conf:/etc/nginx/conf.d/default.conf

  auth-server:
    image: jusuk/auth-server:latest
    ports:
      - "28081:8080"

  goods-server:
    image: jusuk/goods-server:latest
    ports:
      - "28082:8080"
    depends_on:
      - "auth-server"

  alarm-server:
    image: jusuk/alarm-server:latest
    # image: alarm-server:latest
    ports:
      - "28080:8080"
    depends_on:
      - "auth-server"